name: 'O-MVLL Xcode'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: O-MVLL Xcode 14.1
        shell: bash
        run: |
          curl -LO https://open-obfuscator.build38.io/static/omvll-deps-xcode-14_1.tar
          mkdir -p /tmp/third-party-xcode14
          mkdir -p $GITHUB_WORKSPACE/dist
          tar xvf ./omvll-deps-xcode-14_1.tar --directory=/tmp/third-party-xcode14
          docker run --rm \
            -v /tmp/third-party-xcode14:/third-party \
            -v $GITHUB_WORKSPACE:/o-mvll \
            openobfuscator/omvll-xcode:latest bash /o-mvll/scripts/docker/xcode_14_compile.sh
      - name: O-MVLL Signing
        uses: indygreg/apple-code-sign-action@v1.0
        with:
          input_path: ${{ github.workspace }}/src/build_xcode/omvll_unsigned.dylib
          output_path: ${{ github.workspace }}/src/build_xcode/omvll_xcode_14.dylib
          p12_file: ${{ github.workspace }}/scripts/certificates/SigningCertificate.p12
          p12_password: ${{ secrets.certificate_password }}
      - name: Generate deployment tar
        uses: a7ul/tar-action@v1.1.3
        id: compress
        with:
          command: c
          cwd: ${{ github.workspace }}/src/build_xcode/
          files: |
            ./omvll_xcode_14.dylib
          outPath: ${{ github.workspace }}/dist/omvll_xcode_14.tar.gz
      - name: Nightly Deployment
        env:
          OMVLL_S3_KEY: ${{ secrets.OMVLL_S3_KEY }}
          OMVLL_S3_SECRET: ${{ secrets.OMVLL_S3_SECRET }}
        shell: bash
        run: |
          docker run \
            -v $GITHUB_WORKSPACE:/o-mvll \
            -e GITHUB_ACTIONS="true" \
            -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE \
            -e GITHUB_REF=$GITHUB_REF \
            -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            -e OMVLL_S3_KEY=$OMVLL_S3_KEY \
            -e OMVLL_S3_SECRET=$OMVLL_S3_SECRET \
            --rm \
            openobfuscator/deployment python3 /o-mvll/.github/scripts/s3-deploy.py
      - name: Experimental Deployment
        env:
          BUILD38_S3_KEY: ${{ secrets.BUILD38_S3_KEY }}
          BUILD38_S3_SECRET: ${{ secrets.BUILD38_S3_SECRET }}
        shell: bash
        run: |
          docker run \
            -v $GITHUB_WORKSPACE:/o-mvll \
            -e GITHUB_ACTIONS="true" \
            -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE \
            -e GITHUB_REF=$GITHUB_REF \
            -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            -e BUILD38_S3_KEY=$BUILD38_S3_KEY \
            -e BUILD38_S3_SECRET=$BUILD38_S3_SECRET \
            --rm \
            openobfuscator/deployment python3 /o-mvll/.github/scripts/s3-deploy.py
