name: 'O-MVLL Xcode'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: O-MVLL Xcode 14.1
        shell: bash
        run: |
          curl -LO https://open-obfuscator.build38.io/static/omvll-deps-xcode-14_1.tar
          mkdir -p /tmp/third-party-xcode14
          tar xvf ./omvll-deps-xcode-14_1.tar --directory=/tmp/third-party-xcode14
          docker run --rm \
            -v /tmp/third-party-xcode14:/third-party \
            -v $GITHUB_WORKSPACE:/o-mvll \
            openobfuscator/omvll-xcode:latest bash /o-mvll/scripts/docker/xcode_14_compile.sh
          mv $GITHUB_WORKSPACE/src/build_xcode/omvll.dylib $GITHUB_WORKSPACE/src/build_xcode/omvll_unsigned.dylib
      - name: O-MVLL Signing
        uses: indygreg/apple-code-sign-action@v1.0
        with:
          input_path: $GITHUB_WORKSPACE/src/build_xcode/omvll_unsigned.dylib
          output_path: $GITHUB_WORKSPACE/src/build_xcode/omvll.dylib
          p12_file: $GITHUB_WORKSPACE/scripts/certificates/SigningCertificate.p12
          p12_password: ${{ secrets.certificate_password }}
      - name: Generate deployment tar
        shell: bash
        run: |
          mkdir -p $GITHUB_WORKSPACE/dist
          docker run --rm \
            -v /tmp/third-party-xcode14:/third-party \
            -v $GITHUB_WORKSPACE:/o-mvll \
            openobfuscator/omvll-xcode:latest bash python3 /o-mvll/scripts/package.py -t xcode_14 /o-mvll/src/build_xcode/omvll.dylib /o-mvll/dist/omvll_xcode_14.tar.gz
          chown -R 1000:1000 /o-mvll/src/build_xcode
          chown -R 1000:1000 $GITHUB_WORKSPACE/dist
      - name: Nightly Deployment
        env:
          OMVLL_S3_KEY: ${{ secrets.OMVLL_S3_KEY }}
          OMVLL_S3_SECRET: ${{ secrets.OMVLL_S3_SECRET }}
        shell: bash
        run: |
          docker run \
            -v $GITHUB_WORKSPACE:/o-mvll \
            -e GITHUB_ACTIONS="true" \
            -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE \
            -e GITHUB_REF=$GITHUB_REF \
            -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            -e OMVLL_S3_KEY=$OMVLL_S3_KEY \
            -e OMVLL_S3_SECRET=$OMVLL_S3_SECRET \
            --rm \
            openobfuscator/deployment python3 /o-mvll/.github/scripts/s3-deploy.py
      - name: Experimental Deployment
        env:
          BUILD38_S3_KEY: ${{ secrets.BUILD38_S3_KEY }}
          BUILD38_S3_SECRET: ${{ secrets.BUILD38_S3_SECRET }}
        shell: bash
        run: |
          docker run \
            -v $GITHUB_WORKSPACE:/o-mvll \
            -e GITHUB_ACTIONS="true" \
            -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE \
            -e GITHUB_REF=$GITHUB_REF \
            -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            -e BUILD38_S3_KEY=$BUILD38_S3_KEY \
            -e BUILD38_S3_SECRET=$BUILD38_S3_SECRET \
            --rm \
            openobfuscator/deployment python3 /o-mvll/.github/scripts/s3-deploy.py
